FROM golang:1.22-bullseye as builder

WORKDIR $GOPATH/src/obu

COPY . .

RUN go mod download
RUN go mod verify

RUN go build -o bin/obu obu/main.go

FROM gcr.io/distroless/static-debian11


COPY --from=builder /go/src/obu/bin . 

CMD ["obu"] 

#docker build . -f obu/dockerfile -t obu:v2